version: '3.8'
services:
  mongodb:
    image: mongo:6.0.8
    ports: 
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - ${LOCAL_PATH}/mongo-data:/data/db

  ai-resolver-main:
    build: ./ai-resolver-main/
    ports: 
      - "8088:8000"
    environment: 
      - MAIN_APP_ID=${MAIN_APP_ID}
      - MAIN_PROTOCOL=${MAIN_PROTOCOL}
      - MAIN_HOST=${MAIN_HOST}
      - MAIN_PORT=${MAIN_PORT}

      - MIND_MICROSERVICE_PROTOCOL=${MIND_MICROSERVICE_PROTOCOL}
      - MIND_MICROSERVICE_HOST=${MIND_MICROSERVICE_HOST}
      - MIND_MICROSERVICE_PORT=${MIND_MICROSERVICE_PORT}

      - VERSION_BRANCH=${VERSION_BRANCH:-master}

      - DB_HOST=mongodb
      - DB_NAME=ai_resolver
    volumes:
      - ${LOCAL_PATH}:/var/www
      - ${LOCAL_PATH}/composer:/root/.cache/composer
    links:
      - ai-resolver-mind-ms
      - mongodb

  ai-resolver-mind-ms:
    build: ./ai-resolver-mind-ms/
    ports: 
      - "8888:8888"
    environment:
      - MIND_MICROSERVICE_PROTOCOL=${MIND_MICROSERVICE_PROTOCOL}
      - MIND_MICROSERVICE_HOST=${MIND_MICROSERVICE_HOST}
      - MIND_MICROSERVICE_PORT=${MIND_MICROSERVICE_PORT}

      - VERSION_BRANCH=${VERSION_BRANCH:-master}
    volumes:
      - ${LOCAL_PATH}:/var/www